name: Build and Release
on: [push]
jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenCV
        run: ./install-opencv.sh
  build-win:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenCV
        run: install-opencv.bat


